### PR TITLE
add functional_address parameter to address class

### PR DESCRIPTION
**Pull request by fbagagli**
Functional addressing is intended to be a broadcast message. With the ECU and network i worked with, usually is a dedicated address (i.e. FF) not bind to any ECU, but that everyone listen to.
I've made these modification because typically when writing a client some messages must be sent "physically" and some "functional".

With this modification we could use the same Address class and Stack to communicate with a server, avoiding duplication and routing on can bus (route all messages to both stacks)

Let me know if could be useful or if i misunderstood the library design/usage.

Thanks,
francesco

### CODE REVIEW

**Comment by pylessard** [comment]
Hi Francisco,
There is something I don't understand. In the actual implementation, you can use the same stack to send both Physical and Functional messages. By embedding the address type in the Adrress object, you'll then need 2 stacks. But you say otherwise ``With this modification we could use the same Address class and Stack to communicate with a server`` , so I am confused.

Have you seen that when calling the stack.send() method, you can add the address_type as a 2nd parameter?  See this :  https://can-isotp.readthedocs.io/en/latest/isotp/implementation.html#isotp.TransportLayer.send

Can you help me understand the intention?

Thanks!

**Comment by fbagagli** [comment]
Hi,
sure, I'll try to explain better the use case.
A client (address `sa`) that must communicate with a server (address `ta`), must send messages sometimes with address type physical and sometimes functional. In this network (apply to all network i've seen) the functional address is declared as a special target address `fa`  different from the ones of the ecu on the network.

So, the _arbitration id_ that the client must use to send a functional message is composed this way:

    arbitration id = 0x 18DB fa sa

Using the parameter target_address_type (0 for Physical, 1 for Functional) does not generate the correct can_id for this use case. 
Currently your code, during the management of the transmission (protocol.py at line 592), execute:

> arbitration_id = self.address.get_tx_arbitraton_id(popped_object['target_address_type'])

In the case of functional addressing you will obtain the can_id:

    arbitration id = 0x18DB ta sa

that is different from the one that i need because the current Address class use only 2 address (target and source) to compute the arbitration id.

Is more clear the intention now? Or i've misunderstood the code?

Thanks,
Francesco

**Comment by pylessard** [comment]
Ah, ok, I understand the intention now.

I believe this way of doing goes against ISO-26262-2, but I am unsure as I speak, I will have to review the standard.  From what I understand, the standard proposes to change the "DB" part of the address (in your example) while what you see in the field is people changing the target address and the "DB" bytes when sending functional messages.

Maybe it would indeed be a good idea to offer support for what you propose, but I would avoid naming this "functional_address" if it refers to nothing in the standard (from memory), maybe something that makes it clear that it is a replacement target_address for functional message. 

I am very much pro-shortcut, especially in Python projects, but I want to make sure that this won't create other problems such as confusion or address conflict. Also, do you think it could create issues of address conflict, such as functional message interrupting long physical transmission?

Anyway, I'd like to read again the standard before proceeding with this. 

Thank you

**Comment by tpierson-voxx** [comment]
@fbagagli @pylessard I don't believe the intention of this PR was ever implemented. You can use `set_address` to switch between physical and functional addresses, though in practice I found it was easier to add some helper functions which did not require changing the stack:

```
class FunctionalAddress(object):
	def __init__(self, client):
		self._stack = client.conn.isotp_layer

	def __enter__(self):
		self._address = self._stack.address
		self._stack.set_address(ISOTPFuncAddr)

	def __exit__(self, exc_type, exc_val, exc_tb):
		self._stack.set_address(self._address)`

class PhysicalAddress(object):
	def __init__(self, client):
		self._stack = client.conn.isotp_layer

	def __enter__(self):
		self._address = self._stack.address
		self._stack.set_address(ISOTPPhysAddr)

	def __exit__(self, exc_type, exc_val, exc_tb):
		self._stack.set_address(self._address)`


def set_func_address(client):
	client.conn.isotp_layer.set_address(ISOTPFuncAddr)


def set_phys_address(client):
	client.conn.isotp_layer.set_address(ISOTPPhysAddr)
```

You can then change from Physical to Functional addressing by one of the following:

```
with FunctionalAddress(client):
	response = client.read_data_by_identifier(did)
```
	
Or

```
set_func_address(client)
response = client.read_data_by_identifier(did)
...
set_phys_address(client)
```

**Comment by hartkopp** [comment]
Hi,
we've added a new feature for functional addressing to the Linux kernel implementation which will hopefully appear in Linux 5.11:
https://lore.kernel.org/linux-can/20201206144731.4609-1-socketcan@hartkopp.net/T/#u

The change is also in the out-of-tree code: https://github.com/hartkopp/can-isotp/commit/c5b3c717586ffe55570a9e13759b087da729b98f

The idea is just to bind to a tp.tx_id and allow only single frame PDUs for sending.

**Comment by pylessard** [comment]
Hello @hartkopp,
Thank you. Yes, I am aware, I follow each change of your repo :).

I will most likely do something similar during the christmas holidays.  This pull request was meant to receive functional messages with the same rx buffer as physical messages. I've never been confortable to go forwards with that changes and still maintain that 2 stacks should be instanciated to do this.

In any case, I think it is reasonable to allow a Tx-only stack.

**Comment by pylessard** [comment]
I will have to close this, I don't think this should be supported this way. Sorry

**Pull request closed without merging**
