### PR TITLE
Add unit tests for ll_data_length CAN Stack parameter

### PR DESCRIPTION
**Pull request by cpavot**

### CODE REVIEW

**Comment by cpavot** [comment]
Hi, I have implemented some additional unit tests for testing ll_data_length parameter on a CAN-FD bus. Initially, I wanted to parametrize the existing receive and transmit tests using unittest subTest capability. However, it seems the current implementation would require additional rework to better synchronize socket / stack threads (IMHO we should use threading Event objects instead of booleans). So this pull request is not optimum in term of code factorization and not exhaustive in terms of test coverage, but it is still an improvement. :)

**Comment by pylessard** [comment]
Interesting! 
Will review soon. I may merge only after fixing #13

**Comment by cpavot** [comment]
Sure. These unit tests allow to exhibit the issue: https://github.com/pylessard/python-can-isotp/issues/13. 2 tests will fail.
I forgot that you need to configure vcan mtu to 72 to support CAN-FD (to be done while the link is down):
```sudo ip link set vcan0 mtu 72```

**Comment by pylessard** [comment]
Hi,
I have manually merged this in another branch. I think we can close this one

**Pull request closed without merging**
