### PR TITLE
CAN FD messages shall be conveyed in CAN FD frames

### PR DESCRIPTION
**Pull request by cpavot**
In the current implementation, when using a CAN-FD bus, CAN frames are used instead of CAN-FD frames.

### CODE REVIEW

**Comment by pylessard** [comment]
Nice work @cpavot ! 
I am still unsure about something, before merging or modifying, I'd like to have your input. 

I believe the ``is_fd`` property in a CanMessage is only used with python-can. Right now the user set the parameter "is_fd" so that each message that goes out of the TransportLayer has the property ``is_fd`` set, while the user could set the message property himself in its callbacks. Is there an advantage of informing the transport layer about the type of CAN message being exchanged below?   What if we only add a parameter to the CanStack.__init__() function? 

Just a thought.

**Comment by pylessard** [comment]
After reviewing the standard, wouldn't it make more sense to output message with msg.is_fd=True only when tx_data_length is set to a value > 8?

**Comment by hartkopp** [comment]
No, you can have a CAN FD frame with data length == 8 (or 0 .. 8 to be more precise).
The FDF bit is a bit in the bitstream that indicates the frame format. CAN (classic / 2.0) and CAN FD are two really different frame formats that both have a data length, that can not be used to distinguish them.

**Comment by pylessard** [comment]
Understood. Thanks

**Pull request merged**
