### PR TITLE
Possibility to turn off flow control sending on reception of FF

### PR DESCRIPTION
**Pull request by toooooobi**
In many of my projects different ECU´s handling the Flow Control sending. 
It would be beneficial to have a possibility to turn off FC sending on FF rx.

I implemented another parameter which can be passed to the TransportLayer, which by default doesn´t change behavior.

### CODE REVIEW

**Comment by pylessard** [comment]
Hi.
Thank you for the contribution.
Would you mind adding a unit test for your feature and update the documentation as well?

**Comment by hartkopp** [comment]
> In many of my projects different ECU´s handling the Flow Control sending. It would be beneficial to have a possibility to turn off FC sending on FF rx.

@toooooobi : 
Sounds interesting. In fact you switch of the reception of a ISO-TP PDU (so that the sender goes into a timeout state) and still can send PDUs on that ISO-TP channel, right?
Just curious, what is the use-case for such a behaviour?

**Comment by toooooobi** [comment]
@pylessard 
Unfortunately I am not very certain about unit test concept and how to implement. Would you guide me a little?

@hartkopp 
A use case for example could be:
I have two "real" ECUs in an automotive environment. 
Between those two the whole communication is taking place, with one only receiving PDUs and sending flow control.
With this isotp lib running on a raspberry pi the use cases are:
- "Listening mode" - I just want to listen to the communication of rxid and not send any Flow Control frame (because the other ECU is handling that already)
- On top of the listening mode I want to be able to send PDUs on top of listening on the txid (for purpose of triggering some functions/debug modes/whatever).

**Comment by hartkopp** [comment]
> @hartkopp A use case for example could be: I have two "real" ECUs in an automotive environment. Between those two the whole communication is taking place, with one only receiving PDUs and sending flow control. With this isotp lib running on a raspberry pi the use cases are:
> 
>     * "Listening mode" - I just want to listen to the communication of rxid and not send any Flow Control frame (because the other ECU is handling that already)

Ah. Got it. That's why I was asking ...
Fortunately this kind of "listening mode" already exists in the Linux kernel implementation. There is a flag in the socket options called `CAN_ISOTP_LISTEN_MODE` which does exactly what you need: With this flag the communication channel of the two given CAN IDs does not send anything (e.g. FCs) but only 'reads and reassembles' the ISO-TP PDUs and gives them to the userspace.

As you would surely like to monitor both directions you would usually open two of these 'listen only' only sockets to not send FCs from either ECU but reassemble their content.

The can-utils (https://github.com/linux-can/can-utils) tool `isotpsniffer` does that for the Linux kernel implementation (in the case you are using Linux): https://github.com/linux-can/can-utils/blob/master/isotpsniffer.c 

>     * On top of the listening mode I want to be able to send PDUs on top of listening on the txid (for purpose of triggering some functions/debug modes/whatever).

You can always disturb ISO-TP by setting up another channel with identical CAN-IDs or send some FCs. Not sure what you are thinking about here.

**Comment by pylessard** [comment]
I'm closing this pull request. I will push one myself that includes unit test and documentation.
Thank you for raising this issue.

**Pull request closed without merging**
