### PR TITLE
Add mypy typing support

### PR DESCRIPTION
**Pull request by brent-stone**
Initial type stubs for compatibility with mypy for downstream projects relying on can-isotp.

isotp.tpsock.opts typing is left mostly unfinished and there may be a few inaccuracies in the other .pyi proposals.

### CODE REVIEW

**Comment by pylessard** [comment]
Hi @brent-stone ,
I do not know about mypi. Please educate me.  

- What's the purpose of this?
- I see that it add extra files but does not modify the source code, is that what should be expected.
- What could be the drawback of not having the .pyi up to date? How does it affect functionality?
- Do you think this should be added to documentation as well?

Regards

**Comment by brent-stone** [comment]
Hi. There's no effect to anyone not using mypy or other modern python dev tools. For those that are, they'll be able to do automated bug checking thanks to these .pyi descriptions.

Documentation can be automatically generated using the source code and stub files using sphinx if you decide to go that route. 

The downside of the .pyi files getting out of synch with the source is those downstream projects relying on type checking **may** get bugs... but that's true anytime someone moves to a new release of a package without rerunning their tests.

**Comment by pylessard** [comment]
Nice stuff.
Thank you for your contribution

**Comment by pylessard** [comment]
Wow, Sublime Text now gives me hint about my own code.
it was about time I learn about this. Thank you!

**Pull request merged**
